ARG BASE_IMAGE_PREFIX
#FROM ${BASE_IMAGE_PREFIX}alpine:3.10
#FROM arm32v7/php:7.4-apache-buster
#FROM arm32v7/alpine:3.10
FROM arm32v7/nginx

# see hooks/post_checkout
#ARG ARCH
#COPY qemu-${ARCH}-static /usr/bin
COPY qemu-arm-static /usr/bin

# add repository
#RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories

# install VNC & the desktop system
#RUN uname -ar > /uname.build
#RUN apk --update --no-cache add git at
RUN ls -ltr /etc
RUN apt-get update -y && apt-get install -y git at

#RUN apt-get -y update && apt-get install -y git at
RUN git clone git://git.osdn.net/gitroot/epgrec/epgrec.git

RUN cp epgrec/config.php.sample epgrec/config.php
RUN cp epgrec/do-record.sh.sample epgrec/do-record.sh

RUN chmod 777 epgrec/templates_c
RUN chmod 777 epgrec/video
RUN chmod 777 epgrec/thumbs
RUN chmod 777 epgrec/settings
RUN chmod 777 epgrec/cache

# softcas
#ADD ./softcas/libpcsclite.so.1.0.0 /usr/lib64/

#ADD ./do-record.sh epgrec/

EXPOSE 80

RUN mkdir -p /var/www/html
RUN echo "<?php phpinfo(); ?>" > /var/www/html/phpinfo.php
RUN echo "<?php echo \"Hello, PHP on Docker!\"; ?>" > /var/www/html/index.php

#CMD ["php", "/var/www/html/index.php"]
