---
apiVersion: v1
kind: Service
metadata:
  name: epgrec-frontend
spec:
  ports:
  - port: 80
  selector:
    app: epgrec-frontend
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: egprec-frontend
spec:
  selector:
    matchLabels:
      app: epgrec-frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: epgrec-frontend
    spec:
      containers:
      - image: a2ito/epgrec-frontend:latest
        name: epgrec-frontend-php
        env:
          # Use secret in real usage
        - name: LANG
          value: "ja_JP.UTF-8"
        - name: TZ
          value: "Asia/Tokyo"
        ports:
        - containerPort: 80
          name: epgrec-frontend
      - image: a2ito/epgrec-frontend:latest
        name: epgrec-frontend-web
      nodeSelector:
        arch: "arm"
