---
apiVersion: v1
kind: Service
metadata:
  name: epgrec-mysql
  namespace: epgrec
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: epgrec-mysql
  namespace: epgrec
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
        - name: MYSQL_USER
          value: "epgrec"
        - name: MYSQL_PASSWORD
          value: "epgrec"
        - name: MYSQL_DATABASE
          value: "epgrec"
        - name: TZ
          value: "Asia/Tokyo"
        ports:
        - containerPort: 3306
          name: mysql
          #command: ["mysqld", "--character-set-server=utf8", "--collation-server=utf8_unicode_ci"]
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      nodeSelector:
        kubernetes.io/arch: "amd64"
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: pvc-mysql-data
