---
apiVersion: v1
kind: Service
metadata:
  name: epgrec-frontend
  namespace: epgrec
spec:
  ports:
  - port: 80
  selector:
    app: epgrec-frontend
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: egprec-frontend
  namespace: epgrec
spec:
  replicas: 1
  selector:
    matchLabels:
      app: epgrec-frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: epgrec-frontend
    spec:
      containers:
      - image: a2ito/epgrec-frontend:latest-arm
              #- image: php:7.2-fpm
        name: epgrec-frontend-php
        imagePullPolicy: Always
        env:
        - name: LANG
          value: "ja_JP.UTF-8"
        - name: TZ
          value: "Asia/Tokyo"
        ports:
        - containerPort: 80
          name: epgrec-frontend
        volumeMounts:
        - name: rectmp
          mountPath: /temp
      - image: arm32v7/nginx:1.17
        name: epgrec-frontend-web
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      nodeSelector:
        kubernetes.io/arch: "arm"
      volumes:
      - name: rectmp
        persistentVolumeClaim:
          claimName: pvc-rectmp
      - name: nginx-config-volume
        configMap:
          name: configmap-nginx

