---
apiVersion: v1
kind: Service
metadata:
  name: epgrec-frontend
  namespace: epgrec
spec:
  ports:
  - port: 80
  selector:
    app: epgrec-frontend
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: egprec-frontend
  namespace: epgrec
spec:
  selector:
    matchLabels:
      app: epgrec-frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: epgrec-frontend
    spec:
      containers:
      - image: arm32v7/php:7.2-zts-buster
        name: epgrec-frontend-php
        env:
        - name: LANG
          value: "ja_JP.UTF-8"
        - name: TZ
          value: "Asia/Tokyo"
        ports:
        - containerPort: 80
          name: epgrec-frontend
        volumeMounts:
        - name: rectmp
          mountPath: /temp
      - image: arm32v7/nginx:1.17
        name: epgrec-frontend-web
        volumeMounts:
        - name: shared-files
          mountPath: /var/www/html
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      nodeSelector:
        kubernetes.io/arch: "arm"
      volumes:
      - name: rectmp
        persistentVolumeClaim:
          claimName: pvc-rectmp

