---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql-data
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle # Reclaim policies are defined below
  nfs:
    server: 192.168.11.2
    path: /nfsshare/app/epgrec-mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mysql-data
  namespace: epgrec
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
