---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql-data
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle # Reclaim policies are defined below
  hostPath:
    path: /mnt/sharerdvol/nfsshare/app/epgrec-mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mysql-data
  namespace: epgrec
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
