---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-recdata
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle # Reclaim policies are defined below
  nfs:
    server: 192.168.11.2
    path: /dlna

