---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-epgrec-sytem
  namespace: epgrec
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-epgrec-system
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: epgrec-system
  namespace: epgrec
