---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-epgrec-system
  namespace: epgrec
rules:
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles","rolebindings"]
  verbs: ["get","list"]
- apiGroups: ["apps"]
  resources: ["deployments","replicasets","daemonsets","statefulsets"]
  verbs: ["*"]
- apiGroups: ["extensions"]
  resources: ["deployments","replicasets","daemonsets","ingresses"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["services","pods","pods/log","endpoints","persistentvolumeclaims","secrets","configmaps"]
  verbs: ["get","update"]
- apiGroups: ["batch"]
  resources: ["cronjobs","jobs"]
  verbs: ["get","update"]
