version: '2'
services:

  mysql:
    image: mysql:5.6
    container_name: dc-epgrec-mysql
    environment:
      MYSQL_USER: epgrec
      MYSQL_PASSWORD: epgrec
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: epgrec
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --sql-mode=""

  epgrec-frontend-web:
    image: nginx:1.17
    container_name: dc-epgrec-frontend-web
    ports: 
      - "80:80"
    links: 
      - epgrec-frontend-php
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  epgrec-frontend-php:
    image: a2ito/epgrec-frontend:latest-amd64
    container_name: dc-epgrec-frontend-php
    privileged: true
    links: 
      - mysql
    volumes:
      - /dev/:/dev/
    environment:
      TZ: Asia/Tokyo
      LANG: ja_JP.UTF-8
