#!/usr/bin/env bash
set -eu

echo "? build"
source hooks/.config

docker build \
  --build-arg BASE_IMAGE_PREFIX=${BASE_IMAGE_PREFIX} \
  --build-arg ARCH=${ARCH} \
  --file ${DOCKERFILE_PATH} \
  --tag "${IMAGE_NAME}-${ARCH}"  \
    .

