#!/bin/bash

# environment variables
env

# Register qemu-*-static for all supported processors except the 
# current one, but also remove all registered binfmt_misc before
echo "####################################################################"
echo "####################################################################"
echo "####################################################################"
if [ `echo ${IMAGE_NAME} | grep 'arm32v7'` ]; then
  docker run --rm --privileged multiarch/qemu-user-static:register --reset

	BASE_IMAGE_PREFIX=arm32v7
  ARCH=arm

fi
#docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
echo "####################################################################"
echo "####################################################################"
echo "####################################################################"
#docker run --rm -t arm64v8/ubuntu uname -m
